[deps]
Franklin = "713c75ef-9fc9-4b05-94a9-213340da978e"
GR = "28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
NodeJS = "2bd173c7-0d6d-553b-b6af-13a54713934c"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Quadmath = "be4d8f0f-7fa4-5f49-b795-2f01399ab2dd"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"
